contracts:
  azuki: 0xED5AF388653567Af2F388E6224dC7C4b3241C544
  doodles: 0x8a90CAb2b38dba80c64b7734e58Ee1dB38B8992e
  moonbirds: 0x23581767a106ae21c074b2276D25e5C3e136a68b
  clonex: 0x348fc118bcc65a92dc033a951af153d14d945312
  mayc: 0x60E4d786628Fea6478F785A6d7e704777c86a7c6
  pxn: 0x160C404B2b49CBC3240055CEaEE026df1e8497A0
  goblintown: 0xbCe3781ae7Ca1a5e050Bd9C4c77369867eBc307e

covalent:
  endpoint: https://api.covalenthq.com/v1
  # category refers to type of address provided
  categories:
    tokens: tokens
  # topic refers to the type of data to download
    topic:
      nft_token_id: nft_token_ids
      nft_tx: nft_transactions{token_id}
  # For parsing
  tx_metadata: ["block_signed_at"]
  tx_params: ["from", "to", "value"]

  # Conversion of column type
  convert_wei: [value]
  convert_timestamp: [block_signed_at]
  rename_columns:
    block_signed_at: timestamp

  # Filter to primary layer
  filter_columns:
    from:
      condition: "!="
      value: 0x0000000000000000000000000000000000000000
    to:
      condition: "!="
      value: 0x0000000000000000000000000000000000000000
    value:
      condition: ">"
      value: 0

  # Convert to unidirectional
  convert_unidirectional:
    cols:
      from: in
      to: out
    entity_col: entity

  # Project-level aggregation
  groupby: ["timestamp", "collection", "entity", "direction"]
  agg:
    value: sum
  time_cols:
    timestamp: 1W

graph:
  cols: ["timestamp", "collection_from", "collection_to", "value"]
  other_collection_label: O